// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS3N4yEPe3OuJMEsf0e-RgpUlt-dK5-qw',
    appId: '1:37637573970:web:ecab74a276786eca267e8b',
    messagingSenderId: '37637573970',
    projectId: 'cortex-efb27',
    authDomain: 'cortex-efb27.firebaseapp.com',
    storageBucket: 'cortex-efb27.firebasestorage.app',
    measurementId: 'G-SWBLZ50YL8',
  );

  // iOS config from GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWazySm577_xP4IvNe04NuEYN4fcICaw',
    appId: '1:37637573970:ios:a22400e00b7a9b20267e8b',
    messagingSenderId: '37637573970',
    projectId: 'cortex-efb27',
    storageBucket: 'cortex-efb27.firebasestorage.app',
    iosBundleId: 'com.cortex.cortexApp',
  );

  // macOS config - TEMPORARY: Register macOS app in Firebase Console for production
  // Using iOS credentials - will fail until you register macOS in Firebase
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYWazySm577_xP4IvNe04NuEYN4fcICaw',
    appId: '1:37637573970:ios:a22400e00b7a9b20267e8b',
    messagingSenderId: '37637573970',
    projectId: 'cortex-efb27',
    storageBucket: 'cortex-efb27.firebasestorage.app',
    iosBundleId: 'com.cortex.cortexApp',
  );
}